### ISSUE TITLE
Support for types generic over `Empty`

### ISSUE THREAD

**Issue by whalelephant** [pyramation/cosmwasm-typescript-gen#12]
For the case where  `CosmosMsg_for_Empty`  is used in  `ExecuteMsg_for_Empty` over a generic default to `Empty`,
which is in the [definitions](https://github.com/nymlab/vectis/blob/typescript-gen/contracts/proxy/schema/execute_msg_for__empty.json#L234) section of the schema, does not get type generated automatically. 

However, when we [generate it separately](https://github.com/nymlab/vectis/blob/typescript-gen/js-app/types/ProxyContract.ts#L13) due to the casing, its type name is compiled to `CosmosMsgFor_Empty`.

Can we add this to a part of some default wasm message types?

**Comment by whalelephant** [comment]
The expected output for a compatible type is:
```
export type CosmosMsg_for_Empty =
    | {
          bank: BankMsg;
      }
    | {
          custom: Empty;
      }
    | {
          wasm: WasmMsg;
      };
```

**Comment by pyramation** [comment]
try this

```sh
npm install -g cosmwasm-typescript-gen@0.2.6
```

**Comment by pyramation** [comment]
this should fix all the `For_Empty` types
