### ISSUE TITLE
Generate doesn't support optional lists in ExecuteMsg schema

### ISSUE THREAD

**Issue by de-husk** [pyramation/cosmwasm-typescript-gen#17]
Steps to reproduce:
* Checkout latest https://github.com/DA0-DA0/dao-contracts
* Run: `cosmwasm-typescript-gen generate \
    --schema ./contracts/cw-named-groups/schema \
    --out . \
    --name CwNamedGroups`

Error:
```
/usr/local/lib/node_modules/cosmwasm-typescript-gen/node_modules/wasm-ast-types/main/wasm.js:70
      throw new Error('what is type: ' + type);
            ^

Error: what is type: array
    at getType (/usr/local/lib/node_modules/cosmwasm-typescript-gen/node_modules/wasm-ast-types/main/wasm.js:70:13)
    at getPropertyType (/usr/local/lib/node_modules/cosmwasm-typescript-gen/node_modules/wasm-ast-types/main/wasm.js:134:12)
    at /usr/local/lib/node_modules/cosmwasm-typescript-gen/node_modules/wasm-ast-types/main/wasm.js:283:28
    at Array.map (<anonymous>)
    at createTypedObjectParams (/usr/local/lib/node_modules/cosmwasm-typescript-gen/node_modules/wasm-ast-types/main/wasm.js:282:26)
    at createPropertyFunctionWithObjectParamsForExec (/usr/local/lib/node_modules/cosmwasm-typescript-gen/node_modules/wasm-ast-types/main/wasm.js:312:13)
    at /usr/local/lib/node_modules/cosmwasm-typescript-gen/node_modules/wasm-ast-types/main/wasm.js:246:12
    at Array.map (<anonymous>)
    at Object.createExecuteInterface (/usr/local/lib/node_modules/cosmwasm-typescript-gen/node_modules/wasm-ast-types/main/wasm.js:243:59)
    at _callee$ (/usr/local/lib/node_modules/cosmwasm-typescript-gen/main/generate.js:113:29)
```

See: https://github.com/DA0-DA0/dao-contracts/pull/347#issuecomment-1152760309

**Comment by de-husk** [comment]
I was able to get the generation working if I removed the [update ExecuteMsg from the schema](https://github.com/DA0-DA0/dao-contracts/blob/main/contracts/cw-named-groups/schema/execute_msg.json#L5-L42).

**Comment by pyramation** [comment]
hey thanks for documenting this!

I'm guessing the way to interpret an array would be a union type, or similar to how they have anyOf. Are there any other array types? Or is it just usually an array of two where the 2nd element is null?

If you change the type to just an array, I'm guessing only downside for now is that the field isn't marked or optional or nullable, but stoked that you weren't completely blocked! I'll get to this asap

**Comment by pyramation** [comment]
@de-husk I added the contract to a fixture so I can test and we can point to code where it does or doesn't work.

I believe I have a fix, can you check these and see if it looks ok?

https://github.com/pyramation/cosmwasm-typescript-gen/pull/18/commits/5455bbae6878baeec4ef950b10523a20250fff29
https://github.com/pyramation/cosmwasm-typescript-gen/pull/18/commits/189e0df140499742552046d1c9dfc74ef2a43f52

**Comment by pyramation** [comment]
https://github.com/pyramation/cosmwasm-typescript-gen/pull/18

**Comment by de-husk** [comment]
Thanks for the super fast fix!

These optional lists look good now:
```
  update: ({
    addressesToAdd,
    addressesToRemove,
    group
  }: {
    addressesToAdd?: string[];
    addressesToRemove?: string[];
    group: string;
...
```

> Are there any other array types? Or is it just usually an array of two where the 2nd element is null?
Looking in dao-dao/contracts, we only have array types where the 2nd element is null. I need to learn more about https://github.com/GREsau/schemars / serde-json, to find out if there are any more of these special array types that we might have to support.

**Comment by pyramation** [comment]
awesome! merged  the PR ;) 
```
npm install -g cosmwasm-typescript-gen@0.2.15
```
